sudo: false
language: go
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
go:
  - "1.10"
before_script:
  - go vet ./...
  - golint -set_exit_status ./...
  - ./scripts/imports
  - ./scripts/format
script:
  - go test -v ./...
